const D=TeaDemo,E=D.esc,$=id=>document.getElementById(id);let data=D.read(),page='dashboard',query='',statusFilter='All',timer;
const modules=[['dashboard','Dashboard'],['products','Products / Drinks'],['categories','Categories'],['promotions','Promotions'],['homepage','Homepage Content'],['gallery','Gallery'],['store','Store Information'],['contact','Contact Information'],['seo','SEO'],['media','Media Library'],['settings','Settings']];
const icon='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></svg>';
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('visible'),4500)}
function save(message='Demo changes saved.'){if(D.save(data)){toast(message);return true}toast('Browser storage is full or unavailable. Export your changes before leaving.');return false}
function button(label,action,id='',secondary=false){return `<button type="button" class="button ${secondary?'secondary':''}" data-action="${action}" data-id="${E(id)}">${label}</button>`}
function head(title,subtitle,action=''){return `<div class="page-head"><div><h1>${title}</h1><p>${subtitle}</p></div>${action}</div>`}
function badge(status){return `<span class="status ${E(status)}">${E(status)}</span>`}
function field(label,key,value='',type='text',wide=false){return `<label class="${wide?'wide':''}">${label}<input name="${key}" type="${type}" value="${E(value)}" ${type==='number'?'min="0" max="999" step="0.01"':''}></label>`}
function area(label,key,value){return `<label class="wide">${label}<textarea name="${key}" aria-label="${E(label)}">${E(value)}</textarea></label>`}
function select(label,key,options,value){return `<label>${label}<select name="${key}">${options.map(o=>`<option ${o===value?'selected':''}>${E(o)}</option>`).join('')}</select></label>`}
function check(label,key,value){return `<label><input name="${key}" type="checkbox" ${value?'checked':''}><span>${label}</span></label>`}
function imageField(value){return `<label class="wide">Image from media library<select name="image">${[...new Set([value,...data.media])].filter(Boolean).map(src=>`<option value="${E(src)}" ${src===value?'selected':''}>${src.startsWith('data:')?'Uploaded image '+(data.media.indexOf(src)+1):E(src.replace('assets/',''))}</option>`).join('')}</select></label><label class="wide">Or upload a JPG, PNG or WebP (up to 600 KB)<input type="file" name="upload" accept="image/jpeg,image/png,image/webp"></label>`}
function table(products,compact=false){return `<div class="table-wrap"><table><thead><tr><th>Drink name</th><th>Category</th><th>Price</th><th>Status</th>${compact?'':'<th>Updated</th>'}<th>Actions</th></tr></thead><tbody>${products.map(p=>`<tr><td><div class="drink-cell"><img src="${D.safeImage(p.image)}" alt=""><div><b>${E(p.name)}</b><small>${p.best?'Best seller':'Sample menu item'}</small></div></div></td><td>${E(p.category)}</td><td>$${Number(p.price).toFixed(2)}</td><td>${badge(p.status)}</td>${compact?'':`<td>${E(p.updated||'2026-09-09')}</td>`}<td><div class="table-actions"><button data-action="edit-drink" data-id="${E(p.id)}">Edit</button>${compact?'':`<button data-action="preview-drink" data-id="${E(p.id)}">Preview</button><button data-action="toggle-drink" data-id="${E(p.id)}">${p.status==='Published'?'Hide':'Show'}</button>`}</div></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No drinks found. Try another filter or add a drink.</td></tr>'}</tbody></table></div>`}
function render(){page=location.hash.slice(1)||'dashboard';if(!modules.some(m=>m[0]===page))page='dashboard';$('navigation').innerHTML=modules.map(([id,label])=>`<a href="#${id}" class="${page===id?'active':''}" ${page===id?'aria-current="page"':''}>${icon}${label}</a>`).join('');$('breadcrumb').textContent=modules.find(m=>m[0]===page)[1];let html='';
 if(page==='dashboard'){const promo=data.promos.find(p=>p.status==='Published');html=head('A fresh start, every day.','Here’s what’s happening on your TEA DONG website.',button('+ Add drink','add-drink'))+`<div class="stats">${[['Total drinks',data.products.length,'Across your menu','♧'],['Active promotions',data.promos.filter(p=>p.status==='Published').length,'Published demo offers','↗'],['Menu categories',data.categories.length,'Flavors for every mood','▦'],['Gallery images',data.gallery.filter(g=>!g.hidden).length,'Visible in your gallery','▧']].map(([name,num,note,symbol])=>`<div class="stat"><div class="top">${name}<span class="stat-icon">${symbol}</span></div><strong>${num}</strong><small>${note}</small></div>`).join('')}</div><div class="dashboard-grid"><div><section class="panel"><div class="panel-heading"><h2>Recently updated drinks</h2><a class="link-button" href="#products">View all →</a></div>${table([...data.products].sort((a,b)=>(b.updated||'').localeCompare(a.updated||'')).slice(0,4),true)}</section><section class="panel"><div class="panel-heading"><h2>Quick actions</h2></div><div class="quick-actions"><button data-action="add-drink"><span>＋</span>Add a new drink</button><button data-action="add-promo"><span>↗</span>Create promotion</button><button data-action="go-homepage"><span>▤</span>Edit homepage</button></div></section></div><div><section class="panel"><div class="panel-heading"><h2>Current promotion</h2>${badge(promo?'Published':'Draft')}</div><div class="panel-body">${promo?`<div class="promo-preview"><h3>${E(promo.title)}</h3><p>${E(promo.description)}</p><img src="${D.safeImage(promo.image)}" alt=""></div><p class="muted" style="font-size:11px;margin:15px 0">Sample promotion · Dates to be confirmed</p>${button('Edit promotion','edit-promo',promo.id,true)}`:'No published promotions yet.'}</div></section><div class="note"><b>Your website, your way.</b><p style="margin:8px 0 0">Edit a drink, then open the website to see your changes. Use both demos on the same local server for automatic sync.</p></div></div></div>`}
 if(page==='products')html=head('Products / Drinks','Keep your menu fresh. All items and prices are sample content.',button('+ Add drink','add-drink'))+`<section class="panel"><div class="toolbar"><input id="search" placeholder="Search drinks…" aria-label="Search drinks" value="${E(query)}"><select id="status-filter" aria-label="Filter status">${['All','Published','Draft','Hidden'].map(s=>`<option ${s===statusFilter?'selected':''}>${s}</option>`).join('')}</select></div><div id="product-table">${filteredTable()}</div></section>`;
 if(page==='categories')html=head('Menu categories','Organize the flavors customers discover.',button('+ Add category','add-category'))+`<div class="panel panel-body category-list">${data.categories.map((c,i)=>`<div class="category-row"><div><b>${E(c)}</b><div class="muted">${data.products.filter(p=>p.category===c).length} drinks</div></div><div>${button('Rename','rename-category',i,true)} ${button('Delete','delete-category',i,true)}</div></div>`).join('')}</div>`;
 if(page==='promotions')html=head('Promotions','Create and manage sample offers for the website.',button('+ Create promotion','add-promo'))+`<div class="media-grid">${data.promos.map(p=>`<article class="media-card"><img src="${D.safeImage(p.image)}" alt="${E(p.title)}"><div class="body">${badge(p.status)}<h3 style="margin-top:12px">${E(p.title)}</h3><p>${E(p.description)}</p><p class="muted">${E(p.start||'Start date unset')} → ${E(p.end||'End date unset')}</p><div class="actions">${button('Edit','edit-promo',p.id,true)}${button(p.status==='Published'?'Archive':'Publish','toggle-promo',p.id,true)}</div></div></article>`).join('')}</div>`;
 if(page==='homepage')html=head('Homepage content','Shape your first impression. Save changes to update the demo.')+`<section class="panel panel-body edit-page"><form id="page-form" data-type="home"><div class="form-grid">${field('Hero title','title',data.home.title,'text',true)}${area('Hero subtitle','subtitle',data.home.subtitle)}${imageField(data.home.image)}${field('Best seller section title','bestTitle',data.home.bestTitle,'text',true)}<label class="wide">Featured drink<select name="featured">${data.products.map(p=>`<option value="${E(p.id)}" ${p.id===data.home.featured?'selected':''}>${E(p.name)}</option>`).join('')}</select></label>${area('Why TEA DONG','why',data.home.why)}${field('Call to action text','cta',data.home.cta,'text',true)}</div><div class="form-actions"><button class="button">Save homepage</button></div></form></section>`;
 if(page==='gallery')html=head('Gallery','Upload, caption and arrange your social moments.',button('+ Add image','add-gallery'))+`<div class="media-grid">${data.gallery.map((g,i)=>`<article class="media-card ${g.hidden?'hidden':''}"><img src="${D.safeImage(g.image)}" alt="${E(g.caption)}"><div class="body"><h3>${E(g.caption)}</h3><p class="muted">Position ${i+1} · ${g.hidden?'Hidden':'Visible'}</p><div class="actions">${button('Edit','edit-gallery',g.id,true)}${button(g.hidden?'Show':'Hide','toggle-gallery',g.id,true)}${i>0?button('← Move up','up-gallery',g.id,true):''}${i<data.gallery.length-1?button('Move down →','down-gallery',g.id,true):''}${button('Delete','delete-gallery',g.id,true)}</div></div></article>`).join('')||'<p>No gallery images yet. Add your first moment.</p>'}</div>`;
 if(page==='store'||page==='contact'){const store=page==='store';html=head(store?'Store information':'Contact information','Placeholder details stay inactive until you add real information.')+`<section class="panel panel-body edit-page"><form id="page-form" data-type="store"><div class="form-grid">${store?field('Store name','name',data.store.name)+field('Opening hours','hours',data.store.hours)+area('Address','address',data.store.address)+field('Google Maps link (https://)','map',data.store.map,'url',true):field('Phone number','phone',data.store.phone,'tel')+field('Telegram link (https://t.me/…)','telegram',data.store.telegram,'url')+field('Instagram link','instagram',data.store.instagram,'url')+field('TikTok link','tiktok',data.store.tiktok,'url')}</div><div class="form-actions"><button class="button">Save information</button></div></form></section>`}
 if(page==='seo')html=head('SEO','Preview the browser title and description for your website.')+`<section class="panel panel-body edit-page"><form id="page-form" data-type="seo">${field('Page title','title',data.seo.title)}${area('Meta description','description',data.seo.description)}<div class="note">Demo metadata updates in the browser. Search engine publishing requires a future production build.</div><div class="form-actions"><button class="button">Save SEO</button></div></form></section>`;
 if(page==='media')html=head('Media library','Client photos and illustrative demo imagery.',button('↑ Upload image','upload-media'))+`<div class="media-grid">${data.media.map((src,i)=>`<article class="media-card"><img src="${D.safeImage(src)}" alt="Media ${i+1}"><div class="body"><h3>${src.startsWith('data:')?'Uploaded image '+(i+1):E(src.replace('assets/',''))}</h3><p class="muted">${src==='assets/Logo.jpg'||src==='assets/Drink.jpg'?'Client supplied':'Illustrative image'}</p><div class="actions">${button('Select','select-media',i,true)}${button('Delete','delete-media',i,true)}</div></div></article>`).join('')}</div>`;
 if(page==='settings')html=head('Settings','Local demo controls. No accounts or authentication are connected.')+`<section class="panel panel-body edit-page"><h3>Language</h3><p class="muted">English is the default. Text is centralized in the demo data model, ready for future Khmer content.</p><h3>Move demo content between files</h3><p>When both pages share a local server, changes sync automatically. For direct file previews, export here and import using “Demo data” in the website footer.</p><div class="form-actions" style="justify-content:flex-start">${button('Export demo JSON','export-data')}${button('Import demo JSON','import-data','',true)}${button('Reset sample data','reset-data','',true)}</div></section>`;
 $('main').innerHTML=html;
 if($('search'))$('search').oninput=e=>{query=e.target.value;$('product-table').innerHTML=filteredTable()};if($('status-filter'))$('status-filter').onchange=e=>{statusFilter=e.target.value;$('product-table').innerHTML=filteredTable()};if($('page-form'))$('page-form').onsubmit=savePage;
}
function filteredTable(){return table(data.products.filter(p=>p.name.toLowerCase().includes(query.toLowerCase())&&(statusFilter==='All'||p.status===statusFilter)))}
function dialog(title,html,handler){$('dialog-title').textContent=title;$('edit-form').innerHTML=html;$('edit-form').onsubmit=handler;$('editor').showModal()}
async function uploaded(form){const f=form.elements.upload?.files[0];if(!f)return null;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>600*1024)throw Error('Choose a JPG, PNG or WebP smaller than 600 KB.');return await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(Error('The image could not be read.'));reader.readAsDataURL(f)})}
async function formValues(form){const values=Object.fromEntries(new FormData(form));delete values.upload;const image=await uploaded(form);if(image){values.image=image;if(!data.media.includes(image))data.media.push(image)}return values}
async function savePage(e){e.preventDefault();try{const type=e.target.dataset.type,values=await formValues(e.target);data[type]={...data[type],...values};save();render()}catch(err){toast(err.message)}}
function editDrink(id){const p=data.products.find(p=>p.id===id)||{name:'',description:'',category:data.categories[0],price:'',image:data.media[0],status:'Draft'};dialog(id?'Edit drink':'Add a new drink',`<div class="form-grid">${field('Drink name','name',p.name)}${select('Category','category',data.categories,p.category)}${area('Short description','description',p.description)}${field('Price (USD)','price',p.price,'number')}${select('Status','status',['Draft','Published','Hidden'],p.status)}${imageField(p.image)}${check('Featured drink','featured',p.featured)}${check('Best seller','best',p.best)}</div><p class="muted">Publishing only changes this browser demo.</p><div class="form-actions"><button class="button secondary" name="intent" value="draft">Save draft</button><button class="button" name="intent" value="publish">Publish to demo</button></div>`,async e=>{e.preventDefault();try{const values=await formValues(e.target);if(!values.name.trim()||values.price===''||!Number.isFinite(Number(values.price)))throw Error('Add a drink name and valid price.');const updated={...p,...values,id:id||'d'+Date.now(),price:Number(values.price),featured:e.target.elements.featured.checked,best:e.target.elements.best.checked,status:e.submitter.value==='draft'?'Draft':'Published',updated:new Date().toISOString().slice(0,10)};if(id)data.products[data.products.findIndex(p=>p.id===id)]=updated;else data.products.push(updated);if(updated.featured){data.home.featured=updated.id;data.products.forEach(other=>other.featured=other.id===updated.id)}save('Drink saved to the demo.');$('editor').close();render()}catch(err){toast(err.message)}});$('edit-form').elements.name.required=true;$('edit-form').elements.price.required=true}
function editPromo(id){const p=data.promos.find(p=>p.id===id)||{title:'',description:'',image:data.media[0],start:'',end:'',status:'Draft'};dialog(id?'Edit promotion':'Create promotion',`<div class="form-grid">${field('Promotion title','title',p.title,'text',true)}${area('Description','description',p.description)}${imageField(p.image)}${field('Start date','start',p.start,'date')}${field('End date','end',p.end,'date')}${select('Status','status',['Draft','Published','Archived'],p.status)}</div><div class="form-actions"><button class="button">Save promotion</button></div>`,async e=>{e.preventDefault();try{const values=await formValues(e.target);if(!values.title.trim())throw Error('Add a promotion title.');if(values.start&&values.end&&values.end<values.start)throw Error('End date must be on or after the start date.');const updated={...p,...values,id:id||'p'+Date.now()};if(id)data.promos[data.promos.findIndex(p=>p.id===id)]=updated;else data.promos.push(updated);save();$('editor').close();render()}catch(err){toast(err.message)}});$('edit-form').elements.title.required=true}
function editGallery(id){const g=data.gallery.find(g=>g.id===id)||{caption:'',image:data.media[0],hidden:false};dialog(id?'Edit gallery image':'Add gallery image',`${field('Caption','caption',g.caption)}${imageField(g.image)}${check('Hide from website','hidden',g.hidden)}<div class="form-actions"><button class="button">Save image</button></div>`,async e=>{e.preventDefault();try{const values=await formValues(e.target);const updated={...g,...values,id:id||'g'+Date.now(),hidden:e.target.elements.hidden.checked};if(id)data.gallery[data.gallery.findIndex(g=>g.id===id)]=updated;else data.gallery.push(updated);save();$('editor').close();render()}catch(err){toast(err.message)}})}
function confirmAction(title,message,action){dialog(title,`<p>${E(message)}</p><div class="form-actions">${button('Cancel','cancel-dialog','',true)}<button class="button danger">Confirm</button></div>`,e=>{e.preventDefault();action();$('editor').close()})}
function editCategory(index){const old=data.categories[index]||'';dialog(old?'Rename category':'Add category',`${field('Category name','name',old)}<div class="form-actions"><button class="button">Save category</button></div>`,e=>{e.preventDefault();const value=e.target.elements.name.value.trim();if(!value||data.categories.some(c=>c.toLowerCase()===value.toLowerCase()&&c!==old)){toast('Use a unique, non-empty category name.');return}if(old){data.categories[index]=value;data.products.forEach(p=>{if(p.category===old)p.category=value})}else data.categories.push(value);save();$('editor').close();render()})}
function importData(){const input=document.createElement('input');input.type='file';input.accept='application/json';input.onchange=async()=>{try{const value=JSON.parse(await input.files[0].text());if(!Array.isArray(value.products)||!Array.isArray(value.media)||!Array.isArray(value.categories)||!Array.isArray(value.promos)||!Array.isArray(value.gallery)||!value.home||!value.store||!value.seo)throw 0;const before=data;data=value;try{render()}catch(err){data=before;render();throw err}save('Demo data imported.')}catch{toast('Choose a valid TEA DONG demo JSON export.')}};input.click()}
document.addEventListener('click',e=>{const target=e.target.closest('[data-action]');if(!target)return;const {action,id}=target.dataset;
 if(action==='add-drink'||action==='edit-drink')editDrink(id);if(action==='add-promo'||action==='edit-promo')editPromo(id);if(action==='add-gallery'||action==='edit-gallery')editGallery(id);if(action==='go-homepage')location.hash='homepage';if(action==='cancel-dialog')$('editor').close();
 if(action==='preview-drink'){const p=data.products.find(p=>p.id===id);dialog('Drink preview',`<img class="image-preview" src="${D.safeImage(p.image)}" alt="${E(p.name)}"><h2>${E(p.name)}</h2><p>${E(p.description)}</p><p>$${Number(p.price).toFixed(2)} · ${E(p.category)}</p>${badge(p.status)}<p class="muted" style="margin-top:16px">Sample menu preview</p>`,e=>e.preventDefault())}
 if(action==='toggle-drink'){const p=data.products.find(p=>p.id===id);p.status=p.status==='Published'?'Hidden':'Published';p.updated=new Date().toISOString().slice(0,10);save();render()}
 if(action==='toggle-promo'){const p=data.promos.find(p=>p.id===id);p.status=p.status==='Published'?'Archived':'Published';save();render()}
 if(action==='toggle-gallery'){const g=data.gallery.find(g=>g.id===id);g.hidden=!g.hidden;save();render()}
 if(action==='up-gallery'||action==='down-gallery'){const i=data.gallery.findIndex(g=>g.id===id),next=i+(action==='up-gallery'?-1:1);if(next>=0&&next<data.gallery.length){[data.gallery[i],data.gallery[next]]=[data.gallery[next],data.gallery[i]];save();render()}}
 if(action==='delete-gallery')confirmAction('Delete gallery image?','This removes the image from the demo gallery. The media library copy stays available.',()=>{data.gallery=data.gallery.filter(g=>g.id!==id);save();render()});
 if(action==='add-category'||action==='rename-category')editCategory(id===''?-1:Number(id));
 if(action==='delete-category'){const name=data.categories[Number(id)];if(data.products.some(p=>p.category===name)){toast('Move drinks to another category before deleting this one.');return}confirmAction('Delete category?',name,()=>{data.categories.splice(Number(id),1);save();render()})}
 if(action==='upload-media')dialog('Upload image',`<label>JPG, PNG or WebP · up to 600 KB<input name="upload" type="file" accept="image/jpeg,image/png,image/webp" required></label><div class="form-actions"><button class="button">Add to library</button></div>`,async e=>{e.preventDefault();try{const value=await uploaded(e.target);if(value&&!data.media.includes(value))data.media.push(value);save();$('editor').close();render()}catch(err){toast(err.message)}});
 if(action==='select-media'){const src=data.media[Number(id)];dialog('Selected image',`<img class="image-preview" src="${D.safeImage(src)}" alt="Selected media"><p>Use this image in a product, promotion or homepage image selector.</p><div class="form-actions">${button('Use as hero','use-hero',id)}</div>`,e=>e.preventDefault())}
 if(action==='use-hero'){data.home.image=data.media[Number(id)];save('Homepage hero image updated.');$('editor').close()}
 if(action==='delete-media'){const src=data.media[Number(id)],used=src==='assets/Logo.jpg'||data.home.image===src||[...data.products,...data.gallery,...data.promos].some(p=>p.image===src);if(used){toast('This image is in use. Replace its references before deleting it.');return}confirmAction('Delete library image?','Remove this image from the local demo media library?',()=>{data.media.splice(Number(id),1);save();render()})}
 if(action==='export-data')D.exportData(data);if(action==='import-data')importData();if(action==='reset-data')confirmAction('Reset demo content?','This replaces your local demo edits with the original samples. Export first if you want to keep them.',()=>{data=structuredClone(D.defaults);save('Sample data restored.');render()});
});
$('close-dialog').onclick=()=>$('editor').close();$('export').onclick=()=>D.exportData(data);window.addEventListener('hashchange',render);window.addEventListener('storage',e=>{if(e.key===D.key&&!$('editor').open){data=D.read();render()}});render();
