const { chromium } = require('C:/Users/Hi/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path=require('path');const fs=require('fs');const {pathToFileURL}=require('url');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 const page=await browser.newPage({viewport:{width:1440,height:1050}});const errors=[];const checks=[];
 page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);await page.waitForTimeout(1000);
 const check=(condition,label)=>{if(!condition)throw Error(label);checks.push(label);};
 const route=async r=>{await page.locator(`.nav [data-route="${r}"]`).click();};
 const action=async(a)=>page.locator(`[data-action="${a}"]`).first().click();
 await page.screenshot({path:path.join(__dirname,'desktop-dashboard.png'),fullPage:true});
 for(const r of ['children','profiles','plans','progress','sessions','assessments','goals','team','attendance','schedule','staff','communication','reports','analytics','documents','users','activity','settings','dashboard']){await route(r);check(await page.locator('#page').innerText().then(t=>t.length>150),'Rendered '+r);}
 await route('children');await page.locator('#child-search').fill('Sok Dara');check(await page.locator('tbody tr').count()===1,'Child search filters rows');await page.getByRole('button',{name:'Open profile →'}).click();
 await page.getByRole('tab',{name:'Development Profile',exact:true}).click();check(await page.locator('.domain-card').count()===10,'All ten development domains');
 await page.locator('[data-domain="0"]').first().click();await page.locator('[data-skill="0"]').selectOption('4');check(await page.locator('[data-skill="0"]').inputValue()==='4','Skill stage saves');await action('close');
 await route('goals');await action('goal-form');await page.locator('[name="title"]').fill('QA: independently choose a play activity');await page.locator('[name="baseline"]').fill('Uses an adult prompt.');await page.locator('[name="target"]').fill('Chooses independently in 4 of 5 opportunities.');await page.locator('[name="intervention"]').fill('Choice board during play.');await page.getByRole('button',{name:'Save goal',exact:true}).click();check(await page.getByText('QA: independently choose a play activity',{exact:true}).count()===1,'Add goal');
 const goal=page.locator('.goal-card').filter({hasText:'QA: independently choose a play activity'});await goal.getByRole('button',{name:'Update progress'}).click();await page.locator('[name="progress"]').fill('76');await page.locator('[name="stage"]').selectOption('2');await page.locator('[name="observation"]').fill('Participated independently in four opportunities.');await page.getByRole('button',{name:'Save progress'}).click();check(await goal.innerText().then(t=>t.includes('76%')),'Update goal progress');await goal.getByRole('button',{name:'Mark achieved'}).click();check(await goal.innerText().then(t=>t.includes('100%')&&t.includes('Achieved')),'Mark achieved');
 await page.locator('#role-switch').selectOption('2');await route('sessions');await action('session-form');await page.locator('[name="response"]').fill('QA observation: independent choice making.');await page.locator('[name="notes"]').fill('QA INTERNAL NOTE MUST NOT APPEAR TO PARENT');await page.getByRole('button',{name:'Save session'}).click();check(await page.locator('#toast').innerText().then(t=>t.includes('saved')),'Specialist session note saved');
 await route('team');await action('team-form');await page.locator('[name="progress"]').fill('QA team progress');await page.locator('[name="actions"]').fill('Practice communication in two settings.');await page.getByRole('button',{name:'Save team review'}).click();check(await page.getByText('QA team progress',{exact:true}).count()===1,'Team review saved');
 await page.locator('#role-switch').selectOption('6');check(await page.locator('.nav button').count()===5,'Parent has simplified navigation');check(!(await page.locator('#app').innerText()).includes('QA INTERNAL NOTE'),'Parent overview excludes internal notes');await route('reports');check(!(await page.locator('.report').innerText()).includes('QA INTERNAL NOTE'),'Parent report excludes internal notes');await route('sessions');await page.locator('[data-action="session-view"]').first().click();check(!(await page.locator('#modal').innerText()).includes('QA INTERNAL NOTE'),'Parent session detail excludes internal notes');await action('close');
 for(let r=0;r<7;r++){await page.locator('#role-switch').selectOption(String(r));check(await page.locator('#role-switch').inputValue()===String(r),'Role '+r+' renders');if(r>0&&r<6){await route('children');check(await page.locator('tbody tr').count()>0,'Assigned children for role '+r);await route('sessions');const service=['','Special Education','Speech Therapy','Occupational Therapy','Psychology','Physical Therapy'][r];check(await page.locator('tbody tr').allTextContents().then(rows=>rows.every(x=>x.includes(service))),'Role '+r+' sessions are service-scoped');}}
 await page.locator('#role-switch').selectOption('0');await action('language');check(await page.locator('html').getAttribute('lang')==='km','Khmer language switch');await action('language');
 await route('settings');await page.locator('[name="stage0"]').fill('Not yet started');await page.getByRole('button',{name:'Save stage settings'}).click();await route('profiles');await page.locator('[data-domain="0"]').first().click();check(await page.locator('#modal').innerText().then(t=>t.includes('Not yet started')),'Configurable stage labels propagate');await action('close');
 await page.reload();await route('profiles');await page.locator('[data-domain="0"]').first().click();check(await page.locator('[data-skill="0"]').inputValue()==='4','Skill changes persist after reload');await action('close');
 await route('reports');await page.locator('#report-type').selectOption('Goals Status');await action('operations-view');check(await page.locator('#modal').innerText().then(t=>t.includes('QA: independently choose')),'Operations report renders goal data');await action('close');
 const downloadPromise=page.waitForEvent('download');await action('operations-export');const download=await downloadPromise;check(download.suggestedFilename().endsWith('.csv'),'CSV report downloads');
 await action('pdf-report');check(await page.locator('#modal').innerText().then(t=>t.includes('Save as PDF')),'PDF export explains browser save flow');await action('close');
 await route('schedule');const before=await page.locator('.card-head').innerText();await action('week-next');check(await page.locator('.card-head').innerText()!==before,'Calendar week navigation');
 for(const [w,h,name] of [[768,1024,'tablet'],[390,844,'mobile']]){await page.setViewportSize({width:w,height:h});if(w<700)await page.getByRole('button',{name:'Toggle navigation'}).click();await route('dashboard');check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal page overflow '+name);await page.screenshot({path:path.join(__dirname,name+'-dashboard.png'),fullPage:true});}
 await page.setViewportSize({width:1440,height:1050});await route('profiles');await page.screenshot({path:path.join(__dirname,'development-profile.png'),fullPage:true});
 await route('children');await page.locator('[data-route="child"]').first().click();for(const tab of ['Overview','Development Profile','Goals','Sessions','Attendance','Progress','Documents','Parent Notes']){await page.getByRole('tab',{name:tab,exact:true}).click();check((await page.locator('#page').innerText()).length>200,'Child tab '+tab);}
 await route('plans');await action('plan-form');await page.locator('[name="priorities"]').fill('QA: independent participation.');await page.getByRole('button',{name:'Save changes',exact:true}).click();check(await page.getByText('QA: independent participation.',{exact:true}).count()===1,'Plan edits persist');
 await route('assessments');await action('assessment-form');await page.locator('[name="domain"]').selectOption('5');check(await page.locator('[name="skill"] option').first().innerText()==='Pencil grasp','Assessment skills follow selected domain');await page.locator('[name="observation"]').fill('QA fine motor observation');await page.locator('[name="support"]').fill('Visual model');await page.locator('[name="recommendation"]').fill('Continue familiar drawing activities');await page.getByRole('button',{name:'Save review',exact:true}).click();check(await page.getByText('QA fine motor observation',{exact:false}).count()>0,'Development review saves');
 await route('communication');await action('communication-form');await page.locator('[name="reason"]').fill('QA family check-in');await page.locator('[name="notes"]').fill('Discussed familiar play routines.');await page.getByRole('button',{name:'Save communication log'}).click();check(await page.getByText('QA family check-in · 2026-09-12').count()===1,'Communication log saves');
 await route('documents');await action('document-form');await page.locator('[name="name"]').fill('QA fictional document');await page.getByRole('button',{name:'Save changes',exact:true}).click();check(await page.getByText('QA fictional document',{exact:false}).count()>0,'Document metadata saves');
 await route('attendance');await page.locator('[data-attendance="KK-001"]').selectOption('Late');check(await page.locator('[data-attendance="KK-001"]').inputValue()==='Late','Attendance update saves');
 for(const w of [768,390]){await page.setViewportSize({width:w,height:900});for(const r of ['profiles','goals','sessions','progress','reports','schedule']){if(w<700)await page.getByRole('button',{name:'Toggle navigation'}).click();await route(r);check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No overflow '+r+' at '+w);}}
 check(errors.length===0,'No browser JavaScript errors');
 // Restore seed data after mutation tests so the client starts with a clean demo.
 await page.evaluate(()=>localStorage.removeItem('king-kids-demo-v1'));
 fs.writeFileSync(path.join(__dirname,'results.json'),JSON.stringify({date:new Date().toISOString(),checks,errors},null,2));
 console.log(JSON.stringify({passed:checks.length,errors}));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
