const D=TeaDemo,E=D.esc;let data=structuredClone(D.defaults),filter='All';
const $=id=>document.getElementById(id);let toastTimer;
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),4500)}
function card(p){const sold=p.availability==='Sold Out';return `<article class="product-card ${sold?'is-sold-out':''}"><div class="product-photo"><img loading="lazy" src="${D.safeImage(p.image)}" alt="${E(p.name)} — illustrative menu photo">${sold?'<span class="badge sold-out-badge">SOLD OUT</span>':p.best?'<span class="badge">MOST LOVED</span>':''}</div><h3>${E(p.name)}</h3><p>${E(p.description)}</p><div class="price-row"><span>$${Number(p.price).toFixed(2)}</span><button class="add-to-cart" data-add-drink="${E(p.id)}" aria-label="${sold?'Sold out: ':'Add to Cart: '}${E(p.name)}" ${sold?'disabled':''}>${sold?'Sold Out':'+ Add to Cart'}</button></div></article>`}
function render(){document.title=data.seo.title;document.querySelector('meta[name=description]').content=data.seo.description;$('hero-title').innerHTML=data.home.title==='Fresh. Fun. TEA DONG.'?'Fresh. Fun.<br><em>TEA DONG.</em>':E(data.home.title);$('hero-subtitle').textContent=data.home.subtitle;$('hero-image').src=D.safeImage(data.home.image);$('best-title').textContent=data.home.bestTitle;$('why-copy').textContent=data.home.why;$('cta-title').textContent=data.home.cta;
 const published=data.products.filter(p=>p.status==='Published');$('best-grid').innerHTML=published.filter(p=>p.best).slice(0,6).map(card).join('')||'<p>New favorites are on the way.</p>';
 $('categories').innerHTML=['All',...data.categories].map(c=>`<button class="${filter===c?'active':''}" aria-pressed="${filter===c}" data-category="${E(c)}">${E(c)}</button>`).join('');$('menu-grid').innerHTML=published.filter(p=>filter==='All'||p.category===filter).map(card).join('')||'<p>Fresh flavors are coming to this category. Try another.</p>';
 const featured=published.find(p=>p.id===data.home.featured)||published[0];$('featured').hidden=!featured;if(featured){$('featured-name').textContent=featured.name;$('featured-description').textContent=featured.description;$('featured-image').src=D.safeImage(featured.image);$('featured-image').alt=featured.name}
 $('promo-grid').innerHTML=data.promos.filter(p=>p.status==='Published').map(p=>`<article class="promo"><p class="eyebrow">SAMPLE OFFER</p><h3>${E(p.title)}</h3><p>${E(p.description)}</p><a class="text-link" href="#contact">Make it a tea date ↗</a><img loading="lazy" src="${D.safeImage(p.image)}" alt="${E(p.title)}"></article>`).join('')||'<p>Check back for our next sweet deal.</p>';
 $('store-address').textContent=data.store.address;$('store-hours').textContent=data.store.hours;$('gallery-grid').innerHTML=data.gallery.filter(g=>!g.hidden).map(g=>`<figure><img loading="lazy" src="${D.safeImage(g.image)}" alt="${E(g.caption)}"><figcaption>${E(g.caption)}</figcaption></figure>`).join('');}
const icons=['<path d="M20 4C6 2 2 12 8 17s13-1 12-13Z M6 20 16 10"/>','<path d="M5 7h13l-2 14H7L5 7Zm3-4h7M18 9h2v5h-3"/>','<path d="m12 2 2.5 7.5L22 12l-7.5 2.5L12 22l-2.5-7.5L2 12l7.5-2.5Z"/>','<circle cx="12" cy="12" r="9"/><path d="M8 14c2 4 6 4 8 0M8 8v2m8-2v2"/>'];
$('values').innerHTML=['Fresh ingredients|Real flavor, from the first sip.','Made to order|Your cup, made your way.','Fun flavors|Find a new favorite every mood.','Friendly prices|A happy little everyday treat.'].map((v,i)=>`<article class="value"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true">${icons[i]}</svg><h3>${v.split('|')[0]}</h3><p>${v.split('|')[1]}</p></article>`).join('');
$('options').innerHTML=Object.entries({Sweetness:['0%','25%','50%','75%','100%'],Ice:['No Ice','Less Ice','Normal Ice'],Size:['S','M','L']}).map(([name,values])=>`<fieldset class="options"><legend>${name}</legend>${values.map((v,i)=>`<button class="${i===0?'active':''}" aria-pressed="${i===0}">${v}</button>`).join('')}</fieldset>`).join('');
document.addEventListener('click',e=>{const category=e.target.closest('[data-category]');if(category){filter=category.dataset.category;render()}const option=e.target.closest('.options button');if(option){option.parentElement.querySelectorAll('button').forEach(b=>{b.classList.toggle('active',b===option);b.setAttribute('aria-pressed',b===option)})}const drink=e.target.closest('[data-drink]');if(drink){data.home.featured=drink.dataset.drink;render();$('featured').scrollIntoView({behavior:'smooth'})}const contact=e.target.closest('[data-contact]');if(contact){const type=contact.dataset.contact,value=data.store[type];if(!value){toast('Contact details are not available in this demo yet.');return}if(type==='phone'&&/^[+\d ()-]{5,25}$/.test(value)){location.href='tel:'+value;return}try{const url=new URL(value);if(url.protocol!=='https:')throw 0;window.open(url.href,'_blank','noopener,noreferrer')}catch{toast('The shop’s contact link is not confirmed yet.')}}});
$('customize').onclick=()=>{const groups=[...document.querySelectorAll('#options .options')];const options={};groups.forEach(group=>options[group.querySelector('legend').textContent.toLowerCase()]=group.querySelector('.active').textContent);TeaCart.openProduct(data.home.featured,options)};
render();

if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('entered');observer.unobserve(entry.target)}}),{threshold:0.08});document.querySelectorAll('.section,.visit').forEach(section=>observer.observe(section))}
