const sampleBookings=[
{ref:'HSC-DEMO-001',customer:'Sokha Chan',phone:'088 123 •••',service:'Hearing Consultation',date:'2026-07-28',time:'09:30',status:'Pending',submitted:'Today, 08:42'},
{ref:'HSC-DEMO-002',customer:'Dara Lim',phone:'070 456 •••',service:'Audiogram Hearing Test',date:'2026-07-26',time:'10:00',status:'Contacted',submitted:'Today, 07:55'},
{ref:'HSC-DEMO-003',customer:'Srey Mom',phone:'078 789 •••',service:'Hearing Aid Consultation',date:'2026-07-25',time:'14:00',status:'Confirmed',submitted:'Yesterday'},
{ref:'HSC-DEMO-004',customer:'Vannak Keo',phone:'096 234 •••',service:'Device Support',date:'2026-06-18',time:'11:30',status:'Completed',submitted:'Jun 12'},
{ref:'HSC-DEMO-005',customer:'Pisey Touch',phone:'012 345 •••',service:'Speech Support',date:'2026-05-22',time:'15:00',status:'Cancelled',submitted:'May 18'},
{ref:'HSC-DEMO-006',customer:'Rithy Ouk',phone:'097 654 •••',service:'OAE Test',date:'2026-05-10',time:'08:30',status:'No-show',submitted:'May 06'}];
const statusClass=s=>s.toLowerCase().replaceAll(' ','-');
function row(b,compact=false){return `<tr><td><strong>${b.ref}</strong></td><td>${b.customer}</td>${compact?'':`<td>${b.phone}</td>`}<td>${b.service}</td><td>${b.date}</td><td>${b.time}</td><td><span class="badge ${statusClass(b.status)}">${b.status}</span></td>${compact?'':`<td>${b.submitted}</td>`}<td><a class="button" href="booking-detail.html">View</a></td></tr>`}
function renderBookings(){const body=document.querySelector('[data-bookings]');if(!body)return;const q=(document.querySelector('#search')?.value||'').toLowerCase(),status=document.querySelector('#status-filter')?.value||'',service=document.querySelector('#service-filter')?.value||'';const list=sampleBookings.filter(b=>(!q||Object.values(b).join(' ').toLowerCase().includes(q))&&(!status||b.status===status)&&(!service||b.service===service));body.innerHTML=list.map(b=>row(b)).join('')||'<tr><td class="empty" colspan="9">No sample bookings match these filters.</td></tr>'}
document.addEventListener('DOMContentLoaded',()=>{document.querySelector('.mobile-toggle')?.addEventListener('click',()=>document.querySelector('.sidebar')?.classList.toggle('open'));document.querySelector('[data-login]')?.addEventListener('submit',e=>{e.preventDefault();location.href='index.html'});document.querySelectorAll('#search,#status-filter,#service-filter').forEach(x=>x.addEventListener('input',renderBookings));renderBookings();const status=document.querySelector('#detail-status');status?.addEventListener('change',()=>{const badge=document.querySelector('#current-status');badge.textContent=status.value;badge.className=`badge ${statusClass(status.value)}`;document.querySelector('#memory-warning').textContent='Status changed in browser memory only — it will reset when this page is reopened.'});document.querySelector('#export-demo')?.addEventListener('click',()=>{const csv=['Reference,Customer,Service,Date,Status',...sampleBookings.map(b=>[b.ref,b.customer,b.service,b.date,b.status].map(v=>`"${v}"`).join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='hsc-static-demo-bookings.csv';a.click();URL.revokeObjectURL(a.href)})});
