const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.QA_BROWSER || 'msedge'});
 const page=await browser.newPage({viewport:{width:1100,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
 await page.waitForTimeout(2000);
 await page.locator('#screen-home .tab-profile').click();
 await page.locator('#profile-guest-view').getByText('Sign In',{exact:true}).click();
 assert.equal(await page.locator('#screen-login input[type=email]').count(),0);
 await page.locator('#login-phone').fill('+855 12 345 678');
 await page.locator('#login-password').fill('DemoPass123');
 await page.screenshot({path:path.join(__dirname,'phone-login.png')});
 await page.locator('#login-form').getByRole('button',{name:'Log In',exact:true}).click();
 assert.equal(await page.locator('#account-profile-phone').innerText(),'+855 12 345 678');
 assert.equal(await page.evaluate(()=>isLoggedIn),true);
 for(const viewport of [{width:1100,height:1000},{width:390,height:844},{width:375,height:667}]){
  await page.setViewportSize(viewport);
  const scroll=page.locator('#screen-profile > .screen-scroll');
  await scroll.evaluate(e=>e.scrollTop=0);
  const metrics=await scroll.evaluate(e=>({height:e.clientHeight,scroll:e.scrollHeight}));
  assert.ok(metrics.scroll>metrics.height);
  for(const label of ['Personal Information','Consultation History','E-Book Library','Subscription','Notifications','Settings','Language','Sign Out']){
   const row=page.locator('#profile-loggedin-view .menu-item').filter({hasText:label});
   await row.scrollIntoViewIfNeeded();
   assert.equal(await row.isVisible(),true);
  }
  await scroll.evaluate(e=>e.scrollTop=e.scrollHeight);
  const signout=await page.locator('#profile-signout').boundingBox();
  const nav=await page.locator('#screen-profile .tab-bar').boundingBox();
  assert.ok(signout.y+signout.height<=nav.y,'Sign Out must be above bottom navigation');
  await page.screenshot({path:path.join(__dirname,'profile-scroll-'+viewport.width+'x'+viewport.height+'.png')});
 }
 await page.locator('#profile-signout').click();
 assert.equal(await page.getByRole('dialog').isVisible(),true);
 assert.match(await page.getByRole('dialog').innerText(),/Sign out of your account\?/);
 await page.screenshot({path:path.join(__dirname,'signout-confirmation.png')});
 await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();
 assert.equal(await page.evaluate(()=>isLoggedIn),true);
 await page.locator('#profile-signout').click();
 await page.getByRole('dialog').getByRole('button',{name:'Sign Out',exact:true}).click();
 assert.equal(await page.evaluate(()=>isLoggedIn),false);
 assert.equal(await page.locator('#profile-guest-view').isVisible(),true);
 await page.locator('#profile-guest-view').getByText('Create Account',{exact:true}).click();
 assert.equal(await page.locator('#signup-form input[type=email][required]').count(),0);
 await page.locator('#signup-name').fill('Sokha Chan');
 await page.locator('#signup-phone').fill('012 345 678');
 await page.locator('#signup-password').fill('DemoPass123');
 await page.locator('#signup-confirm').fill('Different123');
 await page.locator('#signup-form').getByRole('button',{name:'Sign Up',exact:true}).click();
 assert.match(await page.locator('#signup-error').innerText(),/Passwords do not match/);
 assert.equal(await page.evaluate(()=>isLoggedIn),false);
 await page.locator('#signup-confirm').fill('DemoPass123');
 await page.locator('#signup-form').getByRole('button',{name:'Sign Up',exact:true}).click();
 assert.equal(await page.evaluate(()=>isLoggedIn),true);
 assert.equal(await page.locator('#account-profile-name').innerText(),'Sokha Chan');
 assert.equal(await page.locator('#account-profile-phone').innerText(),'+855 12 345 678');
 await page.locator('#screen-profile > .screen-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);
 await page.locator('#profile-signout').click();
 await page.getByRole('dialog').getByRole('button',{name:'Sign Out',exact:true}).click();
 await page.locator('#profile-guest-view').getByText('Sign In',{exact:true}).click();
 await page.locator('#login-phone').fill('123');await page.locator('#login-password').fill('DemoPass123');
 await page.locator('#login-form').getByRole('button',{name:'Log In',exact:true}).click();
 assert.equal(await page.evaluate(()=>isLoggedIn),false);
 assert.match(await page.locator('#login-error').innerText(),/Cambodian phone number/);
 await page.locator('#screen-login').getByText('Forgot password?',{exact:true}).click();
 await page.locator('#reset-phone').fill('+855 12 345 678');
 await page.locator('#reset-form').getByRole('button',{name:'Request Reset Code',exact:true}).click();
 assert.match(await page.locator('#reset-result').innerText(),/No SMS is sent/);
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({result:'PASS',checks:['Phone/password login to Profile','Cambodian phone normalization','all eight Profile rows reachable','Sign Out above nav at 1100x1000, 390x844 and 375x667','Cancel preserves session','Sign Out returns Guest','phone signup without email','password mismatch rejected','invalid phone rejected','phone password-reset demo'],browserErrors:errors},null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
