const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
const {pathToFileURL}=require('node:url');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.QA_BROWSER || 'msedge'});
 const page=await browser.newPage({viewport:{width:1100,height:1000}});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.resolve(__dirname,'../index.html')).href);
 await page.waitForTimeout(2000);
 const results=[];
 for(const method of ['app','telegram']) for(const video of [false,true]){
  await page.locator('.jump-btn').filter({hasText:'Service / Consultation Intro'}).click();
  await page.locator('#screen-consultation-intro .svc-hub-card').filter({hasText:'Online Consulting'}).click();
  assert.equal(await page.locator('#screen-online-consulting .method-card').count(),2);
  assert.equal(await page.locator('#screen-online-consulting [role=switch]').count(),0);
  assert.doesNotMatch(await page.locator('#screen-online-consulting .screen-content').innerText(),/KHQR|payment|\$15|confirmed|Video/i);
  const card=page.locator('#screen-online-consulting .method-card').nth(method==='app'?0:1);
  await card.getByRole('button',{name:'View Details',exact:false}).click();
  const methodDetail=page.locator('#screen-'+method+'-consulting-detail');
  const toggle=methodDetail.getByRole('switch');
  if((await toggle.getAttribute('aria-checked')==='true')!==video) await toggle.click();
  await methodDetail.getByRole('button',{name:'Back to Online Consulting',exact:true}).click();
  assert.equal(await page.locator('#screen-online-consulting').evaluate(e=>e.classList.contains('active')),true);
  await card.getByRole('button',{name:'View Details',exact:false}).click();
  assert.equal(await toggle.getAttribute('aria-checked'),String(video));
  await page.screenshot({path:path.join(__dirname,method+'-detail.png')});
  await methodDetail.getByRole('button',{name:method==='app'?'Book On-App Consultation':'Request Telegram Consultation',exact:true}).click();
  assert.equal(await page.evaluate(()=>consultation.draft.video),video);
  await page.locator('#flow-date').fill('2026-09-12');
  await page.locator('#flow-time').selectOption('4:00 PM');
  await page.locator('#screen-book-consultation .back-btn').click();
  assert.equal(await methodDetail.evaluate(e=>e.classList.contains('active')),true);
  await methodDetail.getByRole('button',{name:method==='app'?'Book On-App Consultation':'Request Telegram Consultation',exact:true}).click();
  assert.equal(await page.locator('#flow-date').inputValue(),'2026-09-12');
  assert.equal(await page.locator('#flow-time').inputValue(),'4:00 PM');
  await page.locator('#flow-form').getByRole('button',{name:'Continue',exact:true}).click();
  await page.locator('#flow-name').fill('QA Guest '+method);
  await page.locator('#flow-phone').fill('+855 12 345 678');
  if(method==='telegram') await page.locator('#flow-telegram').fill('@qa_guest');
  await page.locator('#flow-note').fill('Routine consultation <test>');
  await page.locator('#flow-form button[type=submit]').click();
  const review=page.locator('#screen-book-consultation');
  assert.match(await review.innerText(),/12 Sept? 2026/);
  assert.match(await review.innerText(),/Routine consultation <test>/);
  await review.getByRole('button',{name:method==='app'?'Pay Now · $15.00':'Submit Consultation Request',exact:true}).click();
  if(method==='app'){
   assert.equal(await page.locator('#screen-khqr').evaluate(e=>e.classList.contains('active')),true);
   assert.equal(await page.evaluate(()=>consultation.appointments.length),results.length);
   assert.match(await page.locator('#screen-khqr').innerText(),/12 Sept? 2026/);
   await page.locator('#screen-khqr .screen-scroll').evaluate(e=>e.scrollTop=260);
   await page.screenshot({path:path.join(__dirname,'khqr-'+(video?'video':'chat')+'.png')});
   await page.locator('#screen-khqr').getByRole('button',{name:'Back to Review',exact:true}).click();
   await review.getByRole('button',{name:'Pay Now · $15.00',exact:true}).click();
   await page.getByRole('button',{name:'I Have Paid / Confirm Payment',exact:true}).click();
  }
  const success=page.locator('#screen-booking-success');
  assert.equal(await success.evaluate(e=>e.classList.contains('active')),true);
  assert.match(await success.innerText(),method==='app'?/Payment Successful/:/Request Sent/);
  await page.screenshot({path:path.join(__dirname,method+'-success.png')});
  await success.getByRole('button',{name:'View Appointment',exact:true}).click();
  const detail=page.locator('#screen-appointment-detail');
  assert.match(await detail.innerText(),method==='app'?/Confirmed/:/Awaiting Payment/);
  assert.equal(await detail.getByRole('button',{name:'Join Consultation',exact:true}).count(),method==='app'?1:0);
  await detail.getByRole('button',{name:method==='app'?'Join Consultation':'Open Telegram',exact:true}).click();
  assert.match(await page.locator('#screen-consultation-room').innerText(),method==='telegram'?/Telegram demo/:video?/Video consultation/:/Chat consultation/);
  await page.getByRole('button',{name:'Back to Appointment',exact:true}).click();
  await page.screenshot({path:path.join(__dirname,method+'-'+(video?'video':'chat')+'.png')});
  const record=await page.evaluate(()=>consultation.appointments[0]);
  assert.equal(record.video,video);assert.equal(record.date,'2026-09-12');assert.equal(record.time,'4:00 PM');
  results.push({method,video,payment:record.payment,status:record.status,reference:record.ref,result:'PASS'});
 }
 assert.equal(new Set(results.map(r=>r.reference)).size,4);
 // Manual Telegram verification and completion are explicitly reviewer-only controls.
 await page.locator('#screen-appointment-detail summary').click();
 await page.getByRole('button',{name:'Simulate Payment Confirmed',exact:true}).click();
 await page.locator('#screen-appointment-detail summary').click();
 await page.getByRole('button',{name:'Simulate Consultation Scheduled',exact:true}).click();
 await page.locator('#screen-appointment-detail summary').click();
 await page.getByRole('button',{name:'Simulate Completed',exact:true}).click();
 await page.getByText('My Appointments',{exact:false}).last().click();
 await page.locator('#appt-tabs').getByRole('button',{name:'Past',exact:true}).click();
 assert.equal(await page.locator('.flow-appt').count(),1);
 await page.locator('.flow-appt').click();
 assert.match(await page.locator('#screen-appointment-detail').innerText(),/Completed/);
 await page.getByText('Online Consulting Detail',{exact:false}).click();
 await page.screenshot({path:path.join(__dirname,'consultation-methods.png')});
 // Phone layout, guest validation, and direct jump guard.
 await page.setViewportSize({width:390,height:844});
 await page.locator('#screen-online-consulting .method-card').first().getByRole('button',{name:'View Details',exact:false}).click();
 await page.locator('#screen-app-consulting-detail').getByRole('button',{name:'Book On-App Consultation',exact:true}).click();
 await page.locator('#flow-form button[type=submit]').click();
 assert.equal(await page.evaluate(()=>consultation.draft.step),1);
 await page.evaluate(()=>showScreen('screen-khqr'));
 assert.equal(await page.locator('#screen-khqr').evaluate(e=>e.classList.contains('active')),false);
 await page.evaluate(()=>showScreen('screen-online-consulting'));
 const overflow=await page.locator('#screen-online-consulting .screen-scroll').evaluate(e=>e.scrollWidth>e.clientWidth);
 assert.equal(overflow,false);
 await page.screenshot({path:path.join(__dirname,'consultation-mobile.png')});
 await page.locator('#screen-online-consulting [data-lang-btn=km]').click();
 assert.equal(await page.evaluate(()=>currentLang),'km');
 await page.locator('#screen-online-consulting [data-lang-btn=en]').click();
 assert.equal(await page.evaluate(()=>currentLang),'en');
 assert.deepEqual(errors,[]);
 console.log(JSON.stringify({results,checks:['unique references','no booking before payment','back from KHQR preserves review','guest validation','input escaped','Telegram status progression','completed appointments in Past','direct KHQR jump guarded','390px layout without horizontal overflow'],browserErrors:errors},null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
