'use strict';
const icons={vehicle:'M3 16v-5l2-6h14l2 6v5M3 11h18M5 16v3M19 16v3M6 14h2M16 14h2',arrow:'M5 12h14m-6-6 6 6-6 6','arrow-up':'M12 19V5m-6 6 6-6 6 6',check:'m5 12 4 4L19 6',menu:'M4 6h16M4 12h16M4 18h16',shield:'M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6l-8-3Zm-4 9 3 3 5-6',chat:'M21 11a8 8 0 0 1-8 8H7l-5 3 2-6a8 8 0 1 1 17-5Z',tool:'m14 6 4-4a6 6 0 0 1-7 8L4 18a2 2 0 0 0 3 3l8-8a6 6 0 0 0 7-7l-4 4-4-4Z',home:'m3 10 9-7 9 7M5 9v12h14V9M9 21v-7h6v7',tag:'M3 3h8l10 10-8 8L3 11V3Zm4 4h.01',phone:'M5 3h4l2 5-3 2a15 15 0 0 0 6 6l2-3 5 2v4a2 2 0 0 1-2 2C9 21 3 15 3 5a2 2 0 0 1 2-2Z',send:'m22 2-7 20-4-9-9-4 20-7ZM11 13 22 2',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0ZM15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',clock:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0ZM12 6v6l4 2',info:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0ZM12 11v6M12 7h.01'};
const icon=name=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name]||icons.arrow}"/></svg>`;
const products=[
 {name:'4T Motorcycle Engine Oil',category:'Motorcycle Engine Oil',image:'motorcycle-oil',specs:['4-stroke motorcycle oil','Ask about viscosity grade'],tag:'ENGINE CARE'},
 {name:'Passenger Car Engine Oil',category:'Car Engine Oil',image:'car-oil',specs:['Passenger car lubricant','Confirm engine requirements'],tag:'ENGINE CARE'},
 {name:'Motorcycle Starter Battery',category:'Motorcycle Batteries',image:'motorcycle-battery',specs:['Motorcycle starting power','Confirm size & terminal layout'],tag:'STARTING POWER'},
 {name:'Car Starter Battery',category:'Car Batteries',image:'car-battery',specs:['Passenger vehicle battery','Ask about capacity & fitment'],tag:'STARTING POWER'}
];
const categories=[['Motorcycle Engine Oil','Lubricants for your daily ride.','motorcycle-oil','4T Motorcycle Engine Oil'],['Car Engine Oil','Engine care for the miles ahead.','car-oil','Passenger Car Engine Oil'],['Motorcycle Batteries','Starting power for two wheels.','motorcycle-battery','Motorcycle Starter Battery'],['Car Batteries','Battery options for your car.','car-battery','Car Starter Battery']];
document.querySelector('#category-grid').innerHTML=categories.map(([name,label,img,product])=>`<a class="category-card" href="#contact" data-product="${product}"><div class="category-image"><img src="assets/${img}.jpg" alt="${name}" loading="lazy" width="240" height="180"></div><h3>${name}</h3><p>${label}</p></a>`).join('');
document.querySelector('#product-grid').innerHTML=products.map(p=>`<article class="product-card"><div class="product-image"><span class="product-tag">${p.tag}</span><img src="assets/${p.image}.jpg" alt="${p.name} — illustrative demo product" loading="lazy" width="400" height="300"></div><div class="product-body"><p class="product-category">${p.category}</p><h3>${p.name}</h3><div class="product-specs">${p.specs.map(s=>`<span>${s}</span>`).join('')}</div><div class="product-bottom"><span>Contact for Price</span><button type="button" class="ask-price" data-product="${p.name}" aria-label="Ask for price: ${p.name}">Ask for Price ${icon('arrow')}</button></div></div></article>`).join('');
document.querySelectorAll('[data-icon]').forEach(el=>{el.outerHTML=icon(el.dataset.icon)});
const menu=document.querySelector('.menu-toggle');const navigation=document.querySelector('#navigation');
function closeMenu(){navigation.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation')}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';navigation.classList.toggle('open',open);menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation')});
navigation.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&navigation.classList.contains('open')){closeMenu();menu.focus()}});
document.addEventListener('click',e=>{if(!e.target.closest('.nav-wrap'))closeMenu()});
document.querySelectorAll('[data-product]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();document.querySelector('#product-select').value=el.dataset.product;document.querySelector('#contact').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});document.querySelector('#product-select').focus({preventScroll:true});document.querySelector('#form-status').textContent=''}));
document.querySelectorAll('[data-contact]').forEach(el=>el.addEventListener('click',()=>{document.querySelector('#contact-status').textContent=`${el.dataset.contact} details: To Be Confirmed. Contact information will be added after client approval.`}));
document.querySelector('#inquiry-form').addEventListener('submit',e=>{e.preventDefault();document.querySelector('#form-status').textContent='Demo preview only — your inquiry has not been sent or saved. The live contact method will be added after client confirmation.'});
document.querySelector('#year').textContent=new Date().getFullYear();
if('IntersectionObserver' in window&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('reveal');observer.unobserve(entry.target)}})},{threshold:.08});document.querySelectorAll('.product-card,.why-grid article,.confidence').forEach(el=>observer.observe(el))}
