const fs=require('fs');
function edit(p,fn){fs.writeFileSync(p,fn(fs.readFileSync(p,'utf8')));}
const html=[...fs.readdirSync('.').filter(x=>x.endsWith('.html')),...fs.readdirSync('admin').filter(x=>x.endsWith('.html')).map(x=>'admin/'+x)];
// Named form controls must not collide with HTMLFormElement.name / id.
for(const p of html)edit(p,s=>s.replace(/\bform\.(\w+)\.value/g,'form.elements.namedItem("$1").value').replace(/\bform\.confirm\.checked/g,'form.elements.namedItem("confirm").checked').replace(/src=""/g,'src="'+(p.startsWith('admin/')?'../':'')+'assets/images/course-maintenance.jpg"').replace(/assets\/images\/([\w-]+)\.svg/g,'assets/images/$1.jpg').replace(/href="#"/g,'href="contact.html"').replace(/This cannot be undone in the demo session\./g,'Existing registrations will be retained.').replace(/Featured Image URL|Course Image URL|Image URL/g,'Local image path').replace(/placeholder="https:\/\/\.\.\."/g,'placeholder="assets/images/course-electrical.jpg"'));
edit('js/data.js',s=>s.replace(/  \/\* All images below[\s\S]*?  var IMG/,'  // Locally stored technical stock photography; see IMAGE-SOURCES.md.\n  var IMG').replace(/assets\/images\/([\w-]+)\.svg/g,'assets/images/$1.jpg').replace('email: "info@mepacademy-demo.kh"','email: ""').replace('address: "Phnom Penh, Cambodia (address to be confirmed)"','address: ""').replace('Reach out by phone, Telegram, or the form below.','Talk to our team about courses, schedules and registration.').replace('Graduation Day Gathering','Technical Team Exercise').replace('Student Spotlight: From Trainee to Working Technician','Student Practical Activity: Reading Technical Plans').replace('A short feature on a recent graduate now applying their training in a full-time technical role.','A guided exercise in reading drawings, identifying components and planning a safe sequence of work.').replace("We're proud to share the story of a recent graduate who completed our Electrical Installation program and has since moved into a full-time technical role. Their journey reflects the practical, hands-on approach at the core of our training philosophy.",'Students work through a technical drawing together, identify the tools required and explain the steps before starting practical work. Instructor feedback helps connect drawing interpretation with safe workshop habits.').replace('Academy Closed for Public Holiday','Academy Schedule Update').replace('Please note our training center will be closed in observance of the upcoming public holiday.','Check the training schedule for current intake dates and available seats.').replace('Our training center and administrative office will be closed in observance of the upcoming public holiday. Classes will resume on the next scheduled training day. Thank you for your understanding.','Evening and weekend study options vary by program. Review the intake schedule and contact the academy before making travel arrangements.').replace('publishDate: "2026-09-10", status: "Draft"','publishDate: "2026-09-10", status: "Published"').replace('      return JSON.parse(raw);',`      var data = JSON.parse(raw);
      if (!data.assetRevision) {
        var seed = seedData();
        ['courses','news','gallery','media'].forEach(function(key){
          (data[key] || []).forEach(function(item){
            var field = key === 'media' ? 'url' : 'image';
            var original = seed[key].find(function(x){return x.id === item.id;});
            if (original && (!item[field] || /\\.svg$|^https?:/.test(item[field]))) item[field] = original[field];
          });
        });
        if (data.settings.email === 'info@mepacademy-demo.kh') data.settings.email = '';
        if (/address to be confirmed/i.test(data.settings.address)) data.settings.address = '';
        if (data.pages.home.cta === 'Explore Courses') data.pages.home.cta = 'Register Now';
        data.assetRevision = 1;
        localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
      }
      return data;`).replace('    } catch (e) {}\n  }\n\n  function reset()',`    } catch (e) { throw new Error('Browser storage is full or unavailable. Your changes were not saved.'); }
  }

  function reset()`));
edit('js/main.js',s=>s.replace("      '<div class=\"lang-toggle\"><span class=\"active\">EN</span><span>KH</span></div>' +\n",'').replace('<nav class="main-nav">','<nav class="main-nav" id="main-nav" aria-label="Main navigation">').replace('aria-label="Toggle menu"','aria-label="Toggle menu" aria-controls="main-nav" aria-expanded="false"').replace('Demonstration build — sample content','Preview · Illustrative content').replace("'<li>' + esc(settings.phone) + ' (Phone / Telegram)</li>'","'<li><a href=\"tel:+85577929360\">' + esc(settings.phone) + '</a><br>Phone / Telegram</li>'").replace('"https://t.me/" + data.settings.telegram.replace(/\\s+/g, "")','MEP.telegramURL(data.settings.telegram)').replace('mainNav.classList.toggle("open");','mainNav.classList.toggle("open");\n        navToggle.setAttribute("aria-expanded", mainNav.classList.contains("open"));').replace('navToggle.textContent = "☰";','navToggle.textContent = "☰"; navToggle.setAttribute("aria-expanded", "false");'));
edit('index.html',s=>s.replace('<a href="register.html" class="btn btn-outline" id="home-hero-cta">Register Now</a>','<a href="schedule.html" class="btn btn-outline" id="home-hero-cta">View Schedule</a>').replace(/      if \(data.pages.home.cta\).*\n/,'').replace('data.intakes.slice(0,5)','data.intakes.filter(function(i){return i.status!=="Closed" && data.courses.some(function(c){return c.id===i.courseId && c.status==="Published";});}).sort(function(a,b){return a.startDate.localeCompare(b.startDate);}).slice(0,5)').replace('    <span class="eyebrow">MEP Technical','    <div class="hero-copy"><span class="eyebrow">MEP Technical').replace('  </div>\n</section>','    </div><figure class="hero-photo"><img src="assets/images/course-electrical.jpg" alt="Electrician practicing wiring installation with protective equipment" fetchpriority="high"><figcaption><span>LEARN BY DOING</span><strong>Real tools. Practical skills.</strong><small>Electrical · Mechanical · Plumbing</small></figcaption></figure>\n  </div>\n</section>'));
edit('about.html',s=>s.replace('<p>MEP Technical and Skills Academy focuses','<p id="about-content">MEP Technical and Skills Academy focuses').replace('      <span class="eyebrow">Why Choose Us</span>\n      <h2>What Sets Our Training Apart</h2>','      <span class="eyebrow">Who We Serve</span>\n      <h2>Skills for the Next Step in Your Working Life</h2>\n      <p>For school leavers exploring a trade, technicians building confidence and working teams developing maintenance skills.</p>').replace('<section class="cta-band">','<section class="section"><div class="container about-grid"><div><span class="eyebrow">Why Technical Skills Matter</span><h2>Better Building Services Start with Skilled People</h2></div><p>From reliable power and water supply to comfortable indoor spaces, technical trades support daily life in Cambodia. Learning to read plans, choose tools, inspect equipment and communicate clearly helps learners approach practical tasks with care.</p></div></section>\n<section class="cta-band">').replace('document.getElementById("about-hero-title").textContent','document.getElementById("about-content").textContent = data.pages.about.content;\n      document.getElementById("about-hero-title").textContent'));
edit('course.html',s=>s.replace('var id = s.qparam("id");','var id = s.qparam("id") || "c1";').replace('return i.status !== "Closed";','return i.status !== "Closed" && i.enrolled < i.maxStudents;').replace('if (nextIntake.status === "Closed")','if (nextIntake.status === "Closed" || nextIntake.enrolled >= nextIntake.maxStudents)').replace('document.getElementById("side-intake").textContent = nextIntake.name;','document.getElementById("side-intake").textContent = nextIntake.name + " · " + s.fmtDate(nextIntake.startDate);'));
edit('schedule.html',s=>s.replace('    <div class="table-wrap">','    <div class="gallery-filters" id="schedule-filters" aria-label="Filter by trade"></div>\n    <div class="table-wrap">').replace('    data.intakes\n      .slice()',`    var selectedCategory = 'All';
    ['All','Electrical','Plumbing','HVAC','Mechanical'].forEach(function(cat){
      var button = document.createElement('button'); button.className='filter-chip'; button.textContent=cat;
      button.addEventListener('click',function(){selectedCategory=cat;render();});
      document.getElementById('schedule-filters').appendChild(button);
    });
    function render(){
    body.innerHTML='';
    document.querySelectorAll('#schedule-filters button').forEach(function(b){b.classList.toggle('active',b.textContent===selectedCategory);b.setAttribute('aria-pressed',b.textContent===selectedCategory);});
    data.intakes
      .filter(function(i){return data.courses.some(function(c){return c.id===i.courseId && c.status==='Published' && (selectedCategory==='All' || c.category===selectedCategory);});})`).replace('      });\n  };','      });\n    if(!body.children.length) body.innerHTML=\'<tr><td colspan="7">No intakes in this category. Please contact the academy for the next schedule.</td></tr>\';\n    }\n    render();\n  };'));
edit('register.html',s=>s.replace('Register / Book Training','Register for Training').replace('reserve your seat','request your place').replace('<form id="reg-form" novalidate>','<ol class="registration-steps"><li>Choose course</li><li>Select intake</li><li>Your details</li></ol><div id="selection-summary" class="selection-summary" aria-live="polite">Choose your program and intake to see your training summary.</div><form id="reg-form" novalidate>').replace('      var name = form.elements.namedItem("name").value.trim();','      var name = form.elements.namedItem("name").value.trim();').replace('setError(form.name,','setError(form.elements.namedItem("name"),').replace('setError(form.phone,','setError(form.elements.namedItem("phone"),').replace('setError(form.course,','setError(form.elements.namedItem("course"),').replace('setError(form.intake,','setError(form.elements.namedItem("intake"),').replace('      if (preselectIntake) intakeSelect.value = preselectIntake;','      if (preselectIntake && Array.from(intakeSelect.options).some(function(o){return o.value===preselectIntake && !o.disabled;})) intakeSelect.value = preselectIntake;').replace('i.status === "Closed" ? " disabled"','(i.status === "Closed" || !seats) ? " disabled"').replace('      var fresh = MEP.load();',`      if (!form.elements.namedItem('email').checkValidity()) { SITE.toast('Please enter a valid email address.'); form.elements.namedItem('email').focus(); return; }
      var fresh = MEP.load();
      var selected = fresh.intakes.find(function(i){return i.id===intake && i.courseId===course;});
      if(!selected || selected.status==='Closed' || selected.enrolled>=selected.maxStudents || !fresh.courses.some(function(c){return c.id===course && c.status==='Published';})) { SITE.toast('This intake is no longer available. Please select another intake.'); return; }
      if(form.dataset.submitted) return;`).replace('"REG-2026-"','"REG-" + new Date().getFullYear() + "-"').replace('      MEP.save(fresh);','      try { MEP.save(fresh); } catch(error) { SITE.toast(error.message); return; }\n      form.dataset.submitted="true";').replace('"https://t.me/" + fresh.settings.telegram.replace(/\\s+/g, "")','MEP.telegramURL(fresh.settings.telegram)').replace('      if (!valid) return;','      if (!valid) { var invalid=form.querySelector(".invalid input,.invalid select"); if(invalid) invalid.focus(); return; }').replace('phone.length < 6','!/^\\+?[\\d\\s()-]{8,18}$/.test(phone)').replace('Thank you for registering with MEP Technical and Skills Academy.','Your registration has been saved in this browser preview.').replace('Our team will contact you to confirm the training schedule and registration details.','Keep your reference number. For a confirmed place, call the academy or contact the team on Telegram.').replace('      populateIntakes(courseSelect.value);','      populateIntakes(courseSelect.value);\n      updateSummary();').replace('    function setError(field, hasError) {',`    var grid=form.querySelector('.form-grid');
    var courseField=courseSelect.closest('.field'), intakeField=intakeSelect.closest('.field');
    grid.prepend(intakeField); grid.prepend(courseField);
    var heading=document.createElement('h3'); heading.className='field full form-section-title'; heading.textContent='Student information'; intakeField.after(heading);
    function updateSummary(){
      var c=data.courses.find(function(x){return x.id===courseSelect.value;});
      var i=data.intakes.find(function(x){return x.id===intakeSelect.value;});
      document.getElementById('selection-summary').innerHTML=c ? '<strong>'+s.esc(c.name)+'</strong><span>'+s.esc(c.duration)+' · '+s.esc(c.level)+'</span><p>'+(i?s.esc(i.name)+' · '+s.fmtDate(i.startDate)+'<br>'+s.esc(i.days)+' · '+s.esc(i.startTime)+'–'+s.esc(i.endTime)+' · '+Math.max(0,i.maxStudents-i.enrolled)+' seats available':'Select an available intake below.')+'</p>' : 'Choose your program and intake to see your training summary.';
    }
    intakeSelect.addEventListener('change',updateSummary); updateSummary();
    function setError(field, hasError) {
      field.setAttribute('aria-invalid',hasError);`));
edit('contact.html',s=>{let start=s.indexOf('    <div class="form-card">'),end=s.indexOf('\n  </div>\n</section>',start);s=s.slice(0,start)+`    <div class="form-card contact-help"><span class="eyebrow">Admissions support</span><h2>Let’s Find Your Training Program</h2><p>Ask about course content, entry requirements, the next available intake or the training location.</p><ul class="mission-list"><li>Choose a program that matches your experience</li><li>Discuss evening and weekend schedules</li><li>Confirm the venue before travelling</li></ul><a class="btn btn-primary btn-block" data-site-phone-href href="tel:+85577929360">Call 077 929 360</a><p class="text-muted" style="margin-top:18px">Already know your course? <a href="register.html">Start your registration →</a></p></div>`+s.slice(end);return s.replace(/    var form = document.getElementById\("contact-form"\);[\s\S]*?    \}\);/,'').replace('Reach out by phone, Telegram, or the form below and our team will respond.','Talk to our team about courses, schedules and registration.');});
edit('news.html',s=>s.replace("'<p class=\"card-desc\">' + s.esc(n.excerpt) + '</p>' +","'<p class=\"card-desc\">' + s.esc(n.excerpt) + '</p>' + '<details class=\"news-detail\"><summary>Read update</summary><p>' + s.esc(n.content) + '</p></details>' +"));
edit('gallery.html',s=>s.replace('A look inside our classrooms, workshops and student activities.','Explore the tools, technical settings and collaborative activities behind practical learning.').replace("'<div class=\"gallery-item\"><img", "'<button class=\"gallery-item\" type=\"button\"><img").replace("'</div></div>');","'</div></button>');"));
edit('admin/media.html',s=>s.replace('This demo library adds an image by URL rather than a real file upload, which will connect to cloud storage in the production build.','Choose a local asset path from assets/images/. Images are shared with the website.').replace('(Math.round(Math.random()*150)+80) + " KB"','"Local asset"'));
edit('js/admin.js',s=>s.replace('{ href: "#", label: "Logout"','{ href: "login.html", label: "Logout"').replace('Admin Dashboard</span>','BizWeb CMS Core</span>').replace('    if (el) el.classList.add("open");',`    if (el) { el._returnFocus=document.activeElement; el.classList.add('open'); document.body.style.overflow='hidden'; var modal=el.querySelector('.a-modal'); modal.setAttribute('role','dialog'); modal.setAttribute('aria-modal','true'); var title=modal.querySelector('h3'); if(title) modal.setAttribute('aria-label',title.textContent); var first=el.querySelector('input:not([type=hidden]),select,textarea,button'); if(first) first.focus(); }`).replace('    if (el) el.classList.remove("open");',`    if (el) { el.classList.remove('open'); document.body.style.overflow=''; if(el._returnFocus) el._returnFocus.focus(); }`).replace('if (e.target === overlay) overlay.classList.remove("open");','if (e.target === overlay) closeModal(overlay.id);'));
// Reusable interaction and accessibility layer on every public and admin page.
for(const p of html)edit(p,s=>s.replace('</head>','<script src="'+(p.startsWith('admin/')?'../':'')+'js/polish.js" defer></script>\n</head>'));
